### ISSUE TITLE
What does 'b' mean in the context of the 'boolf()' method?

### ISSUE THREAD

**Issue by TechFish3000** [Anuken/ExampleMod#44]
within
`Anuken/ExampleMod/scripts/scatter-silo.js`

I was  also wondering, how does the `disabled()` method work? does it disable the button unless the parameter is true or otherwise?

**Comment by Anuken** [comment]
`b` is the button for which disabling is being checked. The function should return `true` if the button should be disabled, `false` otherwise. In this case, `b` is not used, since the button's state doesn't affect whether or not it should get disabled. You could most likely replace it with an empty parameter list `()`.

**Comment by TechFish3000** [comment]
Ok, thanks for the clarification. Visual Studio's intellisense isn't being helpful today.
